package com.application.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * User model class representing a user document in MongoDB.
 * This class contains details about the user including id, email,
 * display name, and profile picture.
 * 
 * Annotations:
 * - {@link Document} indicates that this class is a MongoDB document with the collection name "users".
 * - {@link Data} is a Lombok annotation that generates getters, setters, equals, hashCode, 
 *   toString, and other utility methods automatically.
 * - {@link NoArgsConstructor} generates a no-argument constructor for the class.
 * - {@link AllArgsConstructor} generates a constructor that accepts all fields.
 */
@Document("users")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /**
     * The unique identifier for the user, generated by MongoDB.
     */
    @Id
    private String id;

    /**
     * The user's email address. Should be unique for each user.
     */
    private String email;

    /**
     * The user's display name, shown in the user profile.
     */
    private String displayName;

    /**
     * The URL to the user's profile picture.
     */
    private String profilePicture;
}
